/**
 * WhatsApp Module Constants
 */

export const WHATSAPP_WEBHOOK_ROUTE_PREFIX = '/api/v1/webhooks/whatsapp';
export const WHATSAPP_ADMIN_ROUTE_PREFIX   = '/api/v1/whatsapp';

export const CONVERSATION_CHANNEL_WHATSAPP = 'whatsapp';
export const CONVERSATION_CHANNEL_VOICE    = 'voice';

export const WHATSAPP_INTENT_BOOK_APPOINTMENT   = 'BOOK_APPOINTMENT';
export const WHATSAPP_INTENT_RESCHEDULE         = 'RESCHEDULE_APPOINTMENT';
export const WHATSAPP_INTENT_CANCEL             = 'CANCEL_APPOINTMENT';
export const WHATSAPP_INTENT_CHECK_APPOINTMENT  = 'CHECK_APPOINTMENT';
export const WHATSAPP_INTENT_CHECK_AVAILABILITY = 'CHECK_AVAILABILITY';
export const WHATSAPP_INTENT_CLINIC_INFO        = 'CLINIC_INFORMATION';
export const WHATSAPP_INTENT_DOCTOR_INFO        = 'DOCTOR_INFORMATION';
export const WHATSAPP_INTENT_APPOINTMENT_TYPES  = 'APPOINTMENT_TYPES';
export const WHATSAPP_INTENT_HUMAN_HANDOFF      = 'HUMAN_HANDOFF';
export const WHATSAPP_INTENT_EMERGENCY          = 'EMERGENCY_REQUEST';
export const WHATSAPP_INTENT_UNKNOWN            = 'UNKNOWN';

export const WHATSAPP_INTENTS = [
  WHATSAPP_INTENT_BOOK_APPOINTMENT,
  WHATSAPP_INTENT_RESCHEDULE,
  WHATSAPP_INTENT_CANCEL,
  WHATSAPP_INTENT_CHECK_APPOINTMENT,
  WHATSAPP_INTENT_CHECK_AVAILABILITY,
  WHATSAPP_INTENT_CLINIC_INFO,
  WHATSAPP_INTENT_DOCTOR_INFO,
  WHATSAPP_INTENT_APPOINTMENT_TYPES,
  WHATSAPP_INTENT_HUMAN_HANDOFF,
  WHATSAPP_INTENT_EMERGENCY,
  WHATSAPP_INTENT_UNKNOWN,
] as const;

export type WhatsAppIntent = (typeof WHATSAPP_INTENTS)[number];

export const WHATSAPP_JOB_PROCESS_INBOUND = 'process_inbound';
export const WHATSAPP_JOB_SEND_OUTBOUND   = 'send_outbound';
export const WHATSAPP_JOB_TYPES = [WHATSAPP_JOB_PROCESS_INBOUND, WHATSAPP_JOB_SEND_OUTBOUND] as const;
export type WhatsAppJobType = (typeof WHATSAPP_JOB_TYPES)[number];

export const WHATSAPP_JOB_STATUS_QUEUED           = 'queued';
export const WHATSAPP_JOB_STATUS_PROCESSING       = 'processing';
export const WHATSAPP_JOB_STATUS_PROCESSED        = 'processed';
export const WHATSAPP_JOB_STATUS_FAILED_RETRYABLE = 'failed_retryable';
export const WHATSAPP_JOB_STATUS_FAILED_PERMANENT = 'failed_permanent';
export const WHATSAPP_JOB_TERMINAL_STATUSES       = [WHATSAPP_JOB_STATUS_PROCESSED, WHATSAPP_JOB_STATUS_FAILED_PERMANENT] as const;

export const WHATSAPP_INTEGRATION_STATUS_ACTIVE    = 'active';
export const WHATSAPP_INTEGRATION_STATUS_INACTIVE  = 'inactive';
export const WHATSAPP_INTEGRATION_STATUS_SUSPENDED = 'suspended';

export const WHATSAPP_MSG_INBOUND  = 'inbound';
export const WHATSAPP_MSG_OUTBOUND = 'outbound';

export const WHATSAPP_MAX_TURNS_PER_SESSION       = 20;
export const WHATSAPP_SESSION_WINDOW_MINUTES      = 60;
export const WHATSAPP_DEFAULT_MIN_NOTICE_HOURS    = 2;
export const WHATSAPP_DEFAULT_BOOKING_HORIZON_DAYS = 30;
export const WHATSAPP_JOB_MAX_ATTEMPTS            = 3;
export const WHATSAPP_JOB_LEASE_DURATION_MS       = 2 * 60 * 1000;
export const WHATSAPP_JOB_RETRY_DELAYS_MS         = [1_000, 4_000, 16_000] as const;
export const WHATSAPP_WORKER_POLL_ACTIVE_MS       = 500;
export const WHATSAPP_WORKER_POLL_IDLE_MS         = 3_000;
export const WHATSAPP_WEBHOOK_MAX_BODY_BYTES      = 512 * 1024;
export const META_GRAPH_API_BASE                  = 'https://graph.facebook.com';
export const WHATSAPP_RATE_LIMIT_WINDOW_MS        = 60 * 1000;
export const WHATSAPP_RATE_LIMIT_MAX_MESSAGES     = 15;
